### ISSUE TITLE
Use ionicons’ iOS icons instead of fontawesome icons

### ISSUE THREAD

**Issue by sssoz** [Vitaliy-1/classic#30]

**Comment by Vitaliy-1** [comment]
Maybe keep Ionicons for the next themes. Or you want something specifical from them?

**Comment by Vitaliy-1** [comment]
Not a problem. As I remember I used fontawesome in 2 places: primary menu for mobiles and Bootstrap's Collapse under the authors' list on an article landing page

**Comment by Vitaliy-1** [comment]
Ionicons are added and all dependencies on fontawesome are changed. Can I close the issue?
