### ISSUE TITLE
Use <address> element for footer address 

### ISSUE THREAD

**Issue by sssoz** [Vitaliy-1/classic#43]
Is it possible to markup the addresses in the footer in an `address` element? Or is this an adjustment to be made to OJS, not the theme? This would improve accessibility, but is not priority. 

![screen shot 2018-07-15 at 11 54 33](https://user-images.githubusercontent.com/6668406/42735640-ea91be82-8825-11e8-84e1-c15857729c16.png)

...would look like this:

```html
<address>
      <strong>Journal of Health Sciences Policy</strong><br>
      WAC Bennett Library<br>
      Simon Fraser University<br>
      8888 University Drive<br>
      Burnaby, BC, Canada<br>
      V5A 1S6<br>
      Email: <a href="mailto:info@example.com">info@example.com</a><br>
</address>
```

**Comment by Vitaliy-1** [comment]
That comes from the input field in the admin dashboard and is customized by the user. It can be used not only for address, so we can't do anything here.
