### ISSUE TITLE
Fix XML galley styles

### ISSUE THREAD

**Issue by sssoz** [Vitaliy-1/classic#48]
http://dev-ojs.e-medjournal.com/index.php/sjt/article/view/6/7 

@Vitaliy-1 is there a separate stylesheet for these styles?

**Comment by Vitaliy-1** [comment]
Yep, the plugin's GitHub page is here: https://github.com/Vitaliy-1/JATSParserPlugin
Styles are located here: https://github.com/Vitaliy-1/JATSParserPlugin/tree/master/resources/scss
I compile them with Gulp tasks: https://github.com/Vitaliy-1/JATSParserPlugin/blob/master/gulpfile.js
`gulp sass` for compilation and minification of SCSS files. `gulp watch` to update the minified CSS file after every change on the local machine.

I'm planning to release the plugin after a few weeks. It will work only with themes that use Bootstrap 4+.

**Comment by Vitaliy-1** [comment]
fixed
