### ISSUE TITLE
Should debug scripts be excluded from the release package?

### ISSUE THREAD

**Issue by NateWr** [Vitaliy-1/classic#51]
I notice that there are two JS files that are more than a MB in size. They don't appear to be loaded, since you're always loading the minified versions. Can we exclude these from the release package? The release package is over a MB and it's mostly because of these two files.

In theory, when the config option `enable_minified` is off, the theme should load the unminified scripts. But I think a reasonable case could be made that that only needs to happen on the backend. (It can be useful for debugging reported errors, but may not be commonly needed no the frontend.)

**Comment by Vitaliy-1** [comment]
Thanks for pointing out. I've repacked the release (with most recent changes in master) and update the release tag: https://github.com/Vitaliy-1/classic/releases/tag/1.0.0-1
